### ISSUE TITLE
Live demo link show broken site

### ISSUE THREAD

**Issue by ratanparai** [OpenCodeFoundation/asset-manager#66]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

In the **README** file, there is a link to view live demo. But the site is broken. Nothing works

## Expected behavior

When anyone click the live demo link, they should see a website with latest PR merged to master branch with everything working as expected. 

## Minimal reproduction of the problem with instructions

Visit the demo link - [http://asset-manager.azurewebsites.net/](http://asset-manager.azurewebsites.net/)

**Comment by ratanparai** [comment]
@kajal-alpha, @mahedee  : From which account this live demo is hosted? To fix it I need access to that account or who hosted it can fix it too.

**Comment by kajal-alpha** [comment]
from mahedee bhai account.

**Comment by ratanparai** [comment]
@kajal-alpha : Thank you. I will contact with @mahedee tomorrow and try to fix it 👍

**Comment by ratanparai** [comment]
This issue is solved in PR #69, #70, #73 and #74
