### ISSUE TITLE
update asp.net Core & EF Core Version Update

### ISSUE THREAD

**Issue by kajal-alpha** [OpenCodeFoundation/asset-manager#80]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe:
</code></pre>

## Current behavior

Currently this project with asp.net 2.0 and ef core 2.0.

## Expected behavior

this project should be update with asp.net core 2.1 and ef core 2.1.

**Comment by ratanparai** [comment]
I will update and create a PR soon

**Comment by ratanparai** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sample](https://trello.com/c/3BnXixDA/1-sample)
